---
title: "R vs Pandas"
date: "24 03 2020"
author: "https://datascience-enthusiast.com/R/pandas_datatable.html"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
knitr::knit_engines$set(python = reticulate::eng_python)
```

# Rdatatable

```{r}
library(data.table)

url <- "https://vincentarelbundock.github.io/Rdatasets/csv/datasets/HairEyeColor.csv"

dt <- fread(url)

class(dt)

names(dt)

str(dt)

dim(dt)

nrow(dt)

ncol(dt)

head(dt)

tail(dt)

summary(dt)

# get first three rows
dt[1:3]

# filter ----
dt[Hair == "Black"]
setkey(dt, Hair)
dt["Black"]

dt[Hair == "Black" & Sex == "Male"]
setkey(dt, Hair, Sex)
dt[.("Black", "Male")]

z = dt[Hair== "Black" | Eye == "Brown"]
head(z)

z = dt[Eye %in% c('Blue','Hazel','Green')]
setkey(dt, Eye)
z = dt[c("Blue","Hazel", "Green")]
head(z)

# select ----
z = dt[,.(Eye)]
head(z)

z = dt[,.(Eye,Sex)]
head(z)

# other operations ----
dt[,unique(Eye)]

dt[,max(Freq)]

# summarise ----
dt[,.(Max_freq = max(Freq),
      Min_freq = min(Freq),
      Std_freq = sd(Freq))]

dt[, max(Freq), by = Sex]

dt[,.(Count = .N), by = .(Eye, Sex)]

dt[,.(Count = .N), by = .(Gt50 = Freq > 50)]

dt[1:10,.(Max_freq = max(Freq),
      Min_freq = min(Freq),
      Std_freq = sd(Freq))]

# Remove a column ----
dt[, V1 := NULL]
head(dt)

# Return the first occurance ----
# query = Query the columns of a DataFrame with a boolean expression.
dt[Eye == "Blue"][1]
setkey(dt, Eye)
dt["Blue", mult = "first"]

# Return the last occurance ----
dt[Eye == "Blue"][.N]
setkey(dt, Eye)
dt["Blue", mult = "last"]

# Return a count ----
dt[Eye %in% c("Blue", "Hazel") & Sex == "Male", .N]
setkey(df, Eye, Sex)
df[.(c("Blue","Hazel"), "Male"), .N]

# Count for each group ----
dt[Eye %in% c("Blue", "Hazel") & Sex == "Male", .(count = .N), by = .(Eye, Sex)]
setkey(dt, Eye, Sex)
dt[.(c("Blue","Hazel"), "Male"), .N, by =.EACHI]

# Order in ascending order ----
dt[order(Freq), tail(.SD)]
tail(dt[order(Freq)])

# Order in descending order ----
dt[order(Freq, decreasing = TRUE), tail(.SD)]
tail(setorder(dt, -Freq))

# "Freq" in descending and "Eye" in ascending ----
tail(setorder(dt, -Freq, Eye))

# Rename columns ----
setnames(dt,c("Freq","Eye"),c("Frequency", "Eye_Color"))
tail(dt)

# Unique rows ----
dt[, unique(.SD), .SDcols = c("Eye_Color", "Sex")]
unique(dt[,.(Eye_Color,Sex)])

# Create new column ----
dt[, Eye_Hair := paste0(Eye_Color, Hair)][, head(.SD), .SDcols = c("Eye_Color","Hair","Eye_Hair")]
z = dt[, Eye_Hair := paste(Eye_Color, Hair)][,.(Eye_Color, Hair, Eye_Hair)]
head(z)
```

# Pandas

```{python}
import pandas as pd

url = "https://vincentarelbundock.github.io/Rdatasets/csv/datasets/HairEyeColor.csv"

df = pd.read_csv(url)

type(df)

list(df)

df.dtypes

df.shape

len(df.index)

len(df.columns)

df.head()

df.tail()

df.describe()

# get first three rows
df[0:3]
df.iloc[:3]

# filter ----
df[df.Hair == "Black"]
df[df["Hair"] == "Black"]
df.query("Hair == 'Black'")

df[(df['Hair'] == 'Black') & (df['Sex'] == 'Male')]
df.query("Hair == 'Black' & Sex == 'Male'")

z = df[(df['Hair']=="Black") | (df["Eye"]=="Brown")]
z = df.query("Hair == 'Black' | Eye =='Brown'")
z.head(6)

df[df.Eye.isin(['Blue','Hazel','Green'])].head()

# select ----
df[["Eye"]].head()
df.Eye.head()

df[["Eye","Sex"]].head()

# other operations ----
df["Eye"].unique()

df.Freq.max()

# summarise ----
import numpy as np

pd.DataFrame({'Max_freq': [df.Freq.max()], \
             'Min_freq': [df.Freq.min()],\
             'Std_freq': [np.std(df.Freq)]})
             
df.groupby("Sex").agg({"Freq":"max"})

# agg with dictionary column:function; rename with dictionary old_column_name:new_column_name
df.groupby(["Eye","Sex"]).agg({"Freq":"count"}).rename(columns={"Freq":"Count"})

df.assign(Gt50 = (df.Freq > 50)).groupby("Gt50").agg({"Gt50":"count"})\
.rename(columns ={"Gt50":"Count"})

pd.DataFrame({'Max_freq': [df[0:10].Freq.max()], \
             'Min_freq': [df[0:10].Freq.min()],\
             'Std_freq': [np.std(df[0:10].Freq)]})
             
# Remove a column ----
df.drop('Unnamed: 0', 1).head()

# Return the first occurance ----
# query = Query the columns of a DataFrame with a boolean expression.
df.query("Eye == 'Blue'")[:1]

# Return the last occurance ----
df.query("Eye == 'Blue'")[-1:]

# Return a count ----
df[df.Eye.isin(['Blue','Hazel']) & (df.Sex=="Male")].shape[0]

# Count for each group ----
df[df.Eye.isin(['Blue','Hazel']) & (df.Sex=="Male")].\
groupby(["Eye","Sex"]).agg({"Freq":"count"}).rename(columns={"Freq":"Count"})

# Order in ascending order ----
df.sort_values(by='Freq').tail(6)

# Order in descending order ----
df.sort_values(by='Freq', ascending = False).tail(6)

# "Freq" in descending and "Eye" in ascending ----
df.sort_values(by=['Freq','Eye'], ascending = [False,True]).tail(6)

# Rename columns ----
df.rename(columns = {"Freq":"Frequency","Eye":"Eye_Color"}).tail()

# Unique rows ----
df[["Eye","Sex"]].drop_duplicates()

# Create new column ----
df.assign(Eye_Hair = df.Eye + df.Hair)[["Eye","Hair","Eye_Hair"]].head()
```

